import { NextResponse } from "next/server";
import { glmConfigured } from "@/lib/glm";
import { generateIssueMdx } from "@/lib/draft";
import { githubConfigured, openFilePR } from "@/lib/github";

export const maxDuration = 300;

// Automated weekly issue publisher: generates the issue MDX and opens a
// GitHub pull request adding it to content/issues/. You review and merge;
// Vercel deploys on merge. Nothing is published without your click.
// Trigger: GET /api/publish-issue?secret=<CRON_SECRET>
export async function GET(request: Request) {
  const secret = process.env.CRON_SECRET;
  const provided = new URL(request.url).searchParams.get("secret");
  if (!secret || provided !== secret) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }
  if (!glmConfigured()) {
    return NextResponse.json({ error: "ZAI_API_KEY is not configured." }, { status: 503 });
  }
  if (!githubConfigured()) {
    return NextResponse.json(
      { error: "GitHub publishing isn't configured. Set GITHUB_TOKEN and GITHUB_REPO." },
      { status: 503 },
    );
  }

  const today = new Date().toISOString().slice(0, 10);
  try {
    const mdx = await generateIssueMdx();
    if (!mdx) {
      return NextResponse.json({ error: "Draft generation failed." }, { status: 502 });
    }

    const slug = `auto-${today}`;
    const prUrl = await openFilePR({
      filePath: `content/issues/${slug}.mdx`,
      content: mdx,
      branch: `issue/${today}`,
      commitMessage: `Draft weekly issue (${today})`,
      prTitle: `Weekly issue draft — ${today}`,
      prBody:
        "Auto-generated weekly issue draft from Bazaar Brief's live market feeds.\n\n" +
        "- Review the copy, replace the literal `#N` in the title with the real issue number, and set `featured` if desired.\n" +
        "- Merge to publish (Vercel deploys automatically), or close to discard.\n\n" +
        "Generated by `/api/publish-issue`.",
    });

    return NextResponse.json({ ok: true, pullRequest: prUrl, slug, at: new Date().toISOString() });
  } catch (error) {
    console.error("publish-issue failed", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Publish failed." },
      { status: 502 },
    );
  }
}
